USE materiasTec;

/*USUARIOS*/
INSERT INTO usuario (clave_usuario, titulo, nombre, apellido_paterno, apellido_materno, usuario, contrasena, horas, rol) 
values('U01', 'ING.', 'ANTONIO', 'AGUILA', 'REYES', 'aaguila01', '01123', 5, 'jefe'),
	  ('U02', 'ING.', 'EFRAIN', 'BERMUDEZ', 'GUADALUPE', 'ebermudez02', '02123', 5, 'maestro'),
	  ('U03', 'ING.', 'JOSÉ FERNANDO', 'HERNÁNDEZ', 'RODRÍGUEZ', 'jfhernandez03', '03123', 5, 'maestro'),
	  ('U04', 'ING.', 'MARÍA MINERVA', 'SAUCEDO', 'TORRES ', 'mmsaucedo04', '04123', 5, 'maestro'),
	  ('U05', 'ING.', 'JOSE GERARDO', 'CARPIO', 'FLORES', 'jgcarpio05', '05123', 5, 'maestro'),
	  ('U06', 'ING.', 'LUIS EDUARDO', 'GUTIERREZ', 'AYALA', 'legutierrez06', '06123', 5, 'maestro'),
	  ('U07', 'ING.', 'RUTH', 'SAEZ DE NANCLARES', 'RODRIGUEZ', 'rsaez07', '07123', 5, 'maestro'),
	  ('U08', 'ING.', 'DENY', 'MARTINEZ', 'TREJO', 'dmartinez08', '08123', 5, 'maestro'),
	  ('U09', 'ING.', 'PAOLA VIRGINIA', 'GALVAN', 'JARAMILLO', 'pvgalvan09', '09123', 5, 'maestro'),
	  ('U10', 'ING.', 'JOSE ALEJANDRO', 'RODRIGUEZ', 'RENTERIA', 'jarodriguez10', '10123', 5, 'maestro'),
	  ('U11', 'LIC.', 'IRMA DE JESUS', 'RAMIREZ', 'ALVAREZ', 'iramirez11', '11123', 5, 'maestro'),
	  ('U12', 'ING.', 'ANA COLUMBA ZURITA', 'MARTINEZ', 'AGUILAR', 'aczmartinez12', '12123', 5, 'maestro'),
	  ('U13', 'ING.', 'JOSE ELIAS', 'MARTINEZ', 'ARIAS', 'jemartinez13', '13123', 5, 'maestro'),
	  ('U14', 'ING.', 'LAURA PATRICIA', 'GUEVARA', 'RANGEL', 'lpguevara14', '14123', 5, 'maestro'),
	  ('U15', 'LIC.', 'ROXANA NOEMI', 'MORENO', 'REAL', 'rnmoreno15', '15123', 5, 'maestro'),
	  ('U16', 'ING.', 'EUGENIO CONRADO', 'MARIN', 'GONZALEZ', 'ecmarin16', '16123', 5, 'maestro'),
	  ('U17', 'ING.', 'IVAN', 'VIGUERAS', 'MONTAÑO', 'ivigueras17', '17123', 5, 'maestro'),
	  ('U18', 'ING.', 'ALEJANDRO', 'GARCIA', 'TRUJILLO', 'agarcia18', '18123', 5, 'maestro'),
	  ('U19', 'ING.', 'DENISSE', 'MEDINA', 'LÓPEZ', 'dmedina19', '19123', 5, 'maestro'),
	  ('U20', 'LIC.', 'ELIZABETH', 'CASTELLANOS', 'NOLASCO', 'ecastellanos20', '20123', 5, 'maestro'),
	  ('U21', 'ING.', 'RUBEN', 'TRUJILLO', 'CORONA', 'rtrujillo21', '21123', 5, 'maestro'),
	  ('U22', 'M.C.', 'MARTHA ALICIA', 'ROCHA', 'SANCHEZ', 'marocha22', '22123', 5, 'maestro'),
	  ('U23', 'ING.', 'HECTOR FEDERICO', 'GODINEZ', 'CABRERA', 'hfgodinez23', '23123', 5, 'maestro'),
	  ('U24', 'ING.', 'JUAN IGNACIO', 'GUIZAR', 'RUIZ', 'jiguizar24', '24123', 5, 'maestro'),
	  ('U25', 'ING.', 'LUZ DEL CARMEN', 'RUIZ', 'GAYTAN', 'lcruiz25', '25123', 5, 'maestro'),
	  ('U26', 'ING.', 'CIRINO', 'SILVA', 'TOVAR', 'csilva26', '26123', 5, 'maestro'),
	  ('U27', 'ING.', 'MANUEL', 'ORNELAS', 'RODRIGUEZ', 'mornelas27', '27123', 5, 'maestro'),
	  ('U28', 'DR.', 'JUAN FRANCISCO', 'MOSIÑO', '', 'jfmosino28', '28123', 5, 'maestro'),
	  ('U29', 'ING.', 'OSCAR ANDRES', 'MORALES', 'REYES', 'oamorales29', '29123', 5, 'maestro'),
	  ('U30', 'MTRA.', 'ANGÉLICA JOSEFINA', 'PÉREZ', 'FLORES', 'ajperez30', '30123', 5, 'maestro'),
	  ('U31', 'LIC.', 'ANGELICA MARIA', 'ORTIZ', 'GAUCIN', 'amortiz31', '31123', 5, 'maestro'),
	  ('U32', 'LIC.', 'DAVID EVERARDO', 'LUGO', 'PEDROZA', 'delugo32', '32123', 5, 'maestro'),
	  ('U33', 'LIC.', 'HECTOR JOSE', 'PUGA', 'SOBERANES', 'hjpuga33', '33123', 5, 'maestro'),
	  ('U34', 'ING.', 'JOSE ALFREDO', 'GASCA', 'GONZALEZ', 'jagasca34', '34123', 5, 'maestro'),
	  ('U35', 'ING.', 'CARLOS RAFAEL', 'LEVY', 'ROJAS', 'cflevy35', '35123', 5, 'maestro'),
	  ('U36', 'ING.', 'EDUARDO JOSE', 'PEREZ', 'PINTOR', 'ejperez36', '36123', 5, 'maestro'),
	  ('U37', 'DRA.', 'MARIA DEL ROSARIO', 'BALTAZAR', 'FLORES', 'mbaltazar37', '37123', 5, 'maestro'),
	  ('U38', 'ING.', 'LAURA', 'JUAREZ', 'GUERRA', 'ljuarez38', '38123', 5, 'maestro'),
	  ('U39', 'DR.', 'JUAN MARTIN', 'CARPIO', 'VALADEZ', 'jmcarpio39', '39123', 5, 'maestro'),
	  ('U40', 'ING.', 'MARIA DE LOS ANGELES', 'ARELLANO', 'VERA', 'maarellano40', '40123', 5, 'maestro'),
	  ('U41', 'MTRA.', 'MA. CONCEPCIÓN ROCÍO', 'SÁNCHEZ', 'CANO', 'masanchez41', '41123', 5, 'maestro'),
	  ('U42', 'LIC.', 'GUSTAVO ADOLFO', 'RODRÍGUEZ', 'MUÑOZ', 'garodriguez42', '42123', 5, 'maestro'),
	  ('U43', 'ING.', 'IVAN', 'VIGUERAS', 'MONTAÑO', 'ivigueras43', '43123', 5, 'maestro'),
	  ('U44', 'ING.', 'ANGELICA BENITA', 'HERNANDEZ', 'CARRANZA', 'abhernandez44', '44123', 5, 'maestro'),
	  ('U45', 'ING.', 'MIGUEL ÁNGEL', 'PEÑA', 'LÓPEZ', 'mapena45', '45123', 5, 'maestro'),
	  ('U46', 'DR.', 'RAÚL', 'SANTIAGO', 'MONTERO', 'rsantiago46', '46123', 5, 'maestro'),
	  ('U47', 'DR.', 'VICTOR MANUEL', 'ZAMUDIO', 'RODRIGUEZ', 'vmzamudio47', '47123', 5, 'maestro'),
	  ('U48', 'ING.', 'JUAN CARLOS', 'AGUILERA', 'CRUZ', 'jcaguilera48', '48123', 5, 'maestro'),
	  ('U49', 'ING.', 'LUIS ROBERTO', 'GALLEGOS', 'MUÑOZ', 'lrgallegos49', '49123', 5, 'maestro'),
	  ('U50', 'ING.', 'DOMINGO', 'GARCIA', 'ORNELAS', 'dgarcia50', '50123', 5, 'maestro'),
	  ('U51', 'ING.', 'MA. CONCEPCION', 'SANDOVAL', 'SOLIS', 'masandoval51', '51123', 5, 'maestro'),
	  ('U52', 'ING.', 'PATRICIA MARIA', 'CASTILLO', 'MARTÍNEZ', 'pmcastillo52', '52123', 5, 'maestro'),
	  ('U53', 'LIC.', 'CARLOS ALBERTO', 'TRUJILLO', 'CASTELLANOS', 'catrujillo53', '53123', 5, 'maestro'),
	  ('U54', 'ING.', 'ADOLFO', 'GAMIÑO', 'GUERRERO', 'agamino54', '54123', 5, 'maestro'),
	  ('U55', 'ING.', 'MA. VERONICA', 'TAPIA', 'IBARRA', 'matapia55', '55123', 5, 'maestro'),
	  ('U56', 'ING.', 'JUAN PABLO', 'MURILLO', 'RUIZ', 'jpmurillo56', '56123', 5, 'maestro'),
	  ('U57', 'ING.', 'JAVIER IVAN', 'MANZANARES', 'CUADROS', 'jimanzanares57', '57123', 5, 'maestro'),
	  ('U58', 'M.C.', 'CARLOS', 'LINO', 'RAMIREZ', 'clino58', '58123', 5, 'maestro'),
	  ('U59', 'ING.', 'JOSE LUIS FERNANDO', 'SUAREZ Y GOMEZ', '', 'jflsuarez59', '59123', 5, 'maestro'),
	  ('U60', 'ING.', 'EDNA MILITZA', 'MARTINEZ', 'PRADO', 'emmartinez60', '60123', 5, 'maestro');
	
/*MATERIAS*/
INSERT INTO materia (clave_materia, nombre, abreviatura_carrera, carrera, semestre, horas_t, horas_p, creditos) 
values('ACF0901', 'CÁLCULO DIFERENCIAL', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 1, 3, 2, 5),
	  ('AED1285', 'FUNDAMENTOS DE PROGRAMACIÓN', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 1, 2, 3, 5),
	  ('AEF1041', 'MATEMÁTICAS DISCRETAS', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 1, 3, 2, 5),
	  ('SCH1024', 'TALLER DE ADMINISTRACIÓN', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 1, 1, 3, 4),
	  ('ACC0906', 'FUNDAMENTOS DE INVESTIGACIÓN', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 1, 2, 2, 4),
	  ('ACA0907', 'TALLER DE ÉTICA', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 1, 0, 4, 4),
	  ('ACF0902', 'CÁLCULO INTEGRAL', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 2, 3, 2, 5),
	  ('ACF0903', 'ÁLGEBRA LINEAL', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 2, 3, 2, 5),
	  ('AED1286', 'PROGRAMACIÓN ORIENTADA A OBJETOS', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 2, 2, 3, 5),
	  ('AEC1008', 'CONTABILIDAD FINANCIERA', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 2, 2, 2, 4),
	  ('AEC1058', 'QUÍMICA', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 2, 2, 2, 4),
	  ('AEF1052', 'PROBABILIDAD Y ESTADÍSTICA', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 2, 3, 2, 5),
	  ('ACF0904', 'CÁLCULO VECTORIAL', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 3, 3, 2, 5),
	  ('AED1026', 'ESTRUCTURA DE DATOS', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 3, 2, 3, 5),
	  ('SCF1006', 'FÍSICA GENERAL', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 3, 3, 2, 5),
	  ('SCC1013', 'INVESTIGACIÓN DE OPERACIONES', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 3, 2, 2, 4),
	  ('SCC1005', 'CULTURA EMPRESARIAL', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 3, 2, 2, 4),
	  ('ACD0908', 'DESARROLLO SUSTENTABLE', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 3, 2, 3, 5),
	  ('ACF0905', 'ECUACIONES DIFERENCIALES', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 4, 3, 2, 5),
	  ('SCD1027', 'TÓPICOS AVANZADOS DE PROGRAMACIÓN', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 4, 2, 3, 5),
	  ('SCD1018', 'PRINCIPIOS ELÉCTRICOS Y APLICACIONES DIGITALES', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 4, 2, 3, 5),
	  ('AEF1031', 'FUNDAMENTOS DE BASE DE DATOS', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 4, 3, 2, 5),
	  ('SCD1022', 'SIMULACIÓN', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 4, 2, 3, 5),
	  ('SCC1017', 'MÉTODOS NUMÉRICOS', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 4, 2, 2, 4),
	  ('SCD1003', 'ARQUITECTURA DE COMPUTADORAS', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 5, 2, 3, 5),
	  ('SCA1025', 'TALLER DE BASE DE DATOS', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 5, 0, 4, 4),
	  ('SCC1010', 'GRAFICACIÓN', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 5, 2, 2, 4),
	  ('AEC1034', 'FUNDAMENTOS DE TELECOMUNICACIONES', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 5, 2, 2, 4),
	  ('SCC1007', 'FUNDAMENTOS DE INGENIERÍA DE SOFTWARE', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 5, 2, 2, 4),
	  ('AEC1061', 'SISTEMAS OPERATIVOS', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 5, 2, 2, 4),
	  ('SCC1014', 'LENGUAJES DE INTERFAZ', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 6, 2, 2, 4),
	  ('SCB1001', 'ADMINISTRACIÓN DE BASE DE DATOS', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 6, 1, 4, 5),
	  ('SCD1021', 'REDES DE COMPUTADORAS', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 6, 2, 3, 5),
	  ('SCA1026', 'TALLER DE SISTEMAS OPERATIVOS', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 6, 0, 4, 4),
	  ('SCD1011', 'INGENIERÍA DE SOFTWARE', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 6, 2, 3, 5),
	  ('SCD1015', 'LENGUAJES Y AUTÓMATAS I', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 6, 2, 3, 5),
	  ('SCC1023', 'SISTEMAS PROGRAMABLES', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 7, 2, 2, 4),
	  ('DAD1401', 'BASES DE DATOS AVANZADAS', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 7, 2, 3, 5),
	  ('SCD1004', 'CONMUTACIÓN Y ENRUTAMIENTO EN REDES DE DATOS', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 7, 2, 3, 5),
	  ('SCG1009', 'GESTIÓN DE PROYECTOS DE SOFTWARE', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 7, 3, 3, 6),
	  ('SCD1016', 'LENGUAJES Y AUTÓMATAS II', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 7, 2, 3, 5),
	  ('ACA0909', 'TALLER DE INVESTIGACIÓN I', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 7, 0, 4, 4),
	  ('SCA1002', 'ADMINISTRACIÓN DE REDES', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 8, 0, 4, 4),
	  ('ACA0910', 'TALLER DE INVESTIGACIÓN II', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 8, 0, 4, 4),
	  ('SCC1019', 'PROGRAMACIÓN LÓGICA Y FUNCIONAL', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 8, 2, 2, 4),
	  ('AEB1055', 'PROGRAMACIÓN WEB', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 8, 1, 4, 5),
	  ('DAD1402', 'DESARROLLO DE APLICACIONES EMPRESARIALES', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 8, 2, 3, 5),
	  ('SCC1012', 'INTELIGENCIA ARTIFICIAL', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 9, 2, 2, 4),
	  ('DAD1403', 'PROGRAMACIÓN WEB AVANZADA', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 9, 2, 3, 5),
	  ('DAD1404', 'ARQUITECTURA DE APLICACIONES EMPRESARIALES', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 9, 2, 3, 5),
	  ('DAB1405', 'DESARROLLO DE APLICACIONES PARA DISPOSITIVOS MÓVILES', 'ISX', 'INGENIERÍA EN SISTEMAS COMPUTACIONALES', 9, 2, 3, 5);
	  
INSERT INTO horario (id_usuario,id_materia,clave_horario,clave_grupo,grupo,aula,lunes,martes,miercoles,jueves,viernes,periodo,turno,alumnos)
values(2, 1,'4007','G01','A','D1','','08:45-10:25','','08:45-10:25','09:35-10:25','Agosto-Diciembre/2020','Matutino',34),
	  (3, 1,'4008','G01','B','D2','','07:00-08:40','','07:00-08:40','07:50-08:40','Agosto-Diciembre/2020','Matutino',25),
	  (4, 1,'4009','G03','C','D3','','12:15-13:55','','12:15-13:55','13:05-13:55','Agosto-Diciembre/2020','Matutino',35),
	  (4, 1,'4010','G04','D','D4','','10:30-12:10','','10:30-12:10','11:20-12:10','Agosto-Diciembre/2020','Matutino',30);
	  
	  


	  
	  
	  
	  
	  
	  
	  